### ISSUE TITLE
Pulse Interval vs. BP Counts

### ISSUE THREAD

**Issue by Old-Kinderhook** [christianniebling/peak_detector#9]
A long time ago, we made a function that counts up-up events (times when the pulse interval decreases consecutively and BP increases consecutively 3 times in a row) and down-down events (the reverse). I gave it the pulse interval (difference in time between BP waves) instead of the RR array so that the len of both arrays will always match. However, it is returning 0 for both up and down counts, so something is going on there. We can also look at this together.

**Comment by christianniebling** [comment]
NCS
